scoreboard objectives add thirst dummy
scoreboard objectives add blood dummy
scoreboard objectives add deaths dummy
scoreboard objectives add ak12 dummy
scoreboard objectives add ak47 dummy
scoreboard objectives add ak74 dummy
scoreboard objectives add akm dummy
scoreboard objectives add aug dummy
scoreboard objectives add famas dummy
scoreboard objectives add fnfal dummy
scoreboard objectives add m4 dummy
scoreboard objectives add m16 dummy
scoreboard objectives add sks dummy
scoreboard objectives add stg44 dummy
scoreboard objectives add m60 dummy
scoreboard objectives add rpg7 dummy
scoreboard objectives add rpk dummy
scoreboard objectives add colt_m1892 dummy
scoreboard objectives add colt_python dummy
scoreboard objectives add deagle dummy
scoreboard objectives add fs dummy
scoreboard objectives add glock17 dummy
scoreboard objectives add p350 dummy
scoreboard objectives add tec9 dummy
scoreboard objectives add usp dummy
scoreboard objectives add m1014 dummy
scoreboard objectives add sawedoff dummy
scoreboard objectives add spas12 dummy
scoreboard objectives add mac10 dummy
scoreboard objectives add mp5 dummy
scoreboard objectives add mp7 dummy
scoreboard objectives add mp40 dummy
scoreboard objectives add p90 dummy
scoreboard objectives add ppsh dummy
scoreboard objectives add thompson dummy
scoreboard objectives add ump45 dummy
scoreboard objectives add awm dummy
scoreboard objectives add kar98k dummy
scoreboard objectives add m40 dummy
scoreboard objectives add m110 dummy
scoreboard objectives setdisplay belowname deaths