execute as @s[hasitem={item=pw:ak12, location=slot.weapon.mainhand}, scores={ak12=1..}] run function guns/ak12/fire
execute as @s[hasitem={item=pw:ak12, location=slot.weapon.mainhand}, scores={ak12=..0}] run scriptevent pw:gun_reload_ak12
execute as @s[hasitem={item=pw:ak47, location=slot.weapon.mainhand}, scores={ak47=1..}] run function guns/ak47/fire
execute as @s[hasitem={item=pw:ak47, location=slot.weapon.mainhand}, scores={ak47=..0}] run scriptevent pw:gun_reload_ak47
execute as @s[hasitem={item=pw:ak74, location=slot.weapon.mainhand}, scores={ak74=1..}] run function guns/ak74/fire
execute as @s[hasitem={item=pw:ak74, location=slot.weapon.mainhand}, scores={ak74=..0}] run scriptevent pw:gun_reload_ak74
execute as @s[hasitem={item=pw:akm, location=slot.weapon.mainhand}, scores={akm=1..}] run function guns/akm/fire
execute as @s[hasitem={item=pw:akm, location=slot.weapon.mainhand}, scores={akm=..0}] run scriptevent pw:gun_reload_akm
execute as @s[hasitem={item=pw:aug, location=slot.weapon.mainhand}, scores={aug=1..}] run function guns/aug/fire
execute as @s[hasitem={item=pw:aug, location=slot.weapon.mainhand}, scores={aug=..0}] run scriptevent pw:gun_reload_aug
execute as @s[hasitem={item=pw:famas, location=slot.weapon.mainhand}, scores={famas=1..}] run function guns/famas/fire
execute as @s[hasitem={item=pw:famas, location=slot.weapon.mainhand}, scores={famas=..0}] run scriptevent pw:gun_reload_famas
execute as @s[hasitem={item=pw:fnfal, location=slot.weapon.mainhand}, scores={fnfal=1..}] run function guns/fnfal/fire
execute as @s[hasitem={item=pw:fnfal, location=slot.weapon.mainhand}, scores={fnfal=..0}] run scriptevent pw:gun_reload_fnfal
execute as @s[hasitem={item=pw:m4, location=slot.weapon.mainhand}, scores={m4=1..}] run function guns/m4/fire
execute as @s[hasitem={item=pw:m4, location=slot.weapon.mainhand}, scores={m4=..0}] run scriptevent pw:gun_reload_m4
execute as @s[hasitem={item=pw:m16, location=slot.weapon.mainhand}, scores={m16=1..}] run function guns/m16/fire
execute as @s[hasitem={item=pw:m16, location=slot.weapon.mainhand}, scores={m16=..0}] run scriptevent pw:gun_reload_m16
execute as @s[hasitem={item=pw:sks, location=slot.weapon.mainhand}, scores={sks=1..}] run function guns/sks/fire
execute as @s[hasitem={item=pw:sks, location=slot.weapon.mainhand}, scores={sks=..0}] run scriptevent pw:gun_reload_sks
execute as @s[hasitem={item=pw:stg44, location=slot.weapon.mainhand}, scores={stg44=1..}] run function guns/stg44/fire
execute as @s[hasitem={item=pw:stg44, location=slot.weapon.mainhand}, scores={stg44=..0}] run scriptevent pw:gun_reload_stg44
execute as @s[hasitem={item=pw:m60, location=slot.weapon.mainhand}, scores={m60=1..}] run function guns/m60/fire
execute as @s[hasitem={item=pw:m60, location=slot.weapon.mainhand}, scores={m60=..0}] run scriptevent pw:gun_reload_m60
execute as @s[hasitem={item=pw:rpg7, location=slot.weapon.mainhand}, scores={rpg7=1..}] run function guns/rpg7/fire
execute as @s[hasitem={item=pw:rpg7, location=slot.weapon.mainhand}, scores={rpg7=..0}] run scriptevent pw:gun_reload_rpg7
execute as @s[hasitem={item=pw:rpk, location=slot.weapon.mainhand}, scores={rpk=1..}] run function guns/rpk/fire
execute as @s[hasitem={item=pw:rpk, location=slot.weapon.mainhand}, scores={rpk=..0}] run scriptevent pw:gun_reload_rpk
execute as @s[hasitem={item=pw:colt_m1892, location=slot.weapon.mainhand}, scores={colt_m1892=1..}] run function guns/colt_m1892/fire
execute as @s[hasitem={item=pw:colt_m1892, location=slot.weapon.mainhand}, scores={colt_m1892=..0}] run scriptevent pw:gun_reload_colt_m1892
execute as @s[hasitem={item=pw:colt_python, location=slot.weapon.mainhand}, scores={colt_python=1..}] run function guns/colt_python/fire
execute as @s[hasitem={item=pw:colt_python, location=slot.weapon.mainhand}, scores={colt_python=..0}] run scriptevent pw:gun_reload_colt_python
execute as @s[hasitem={item=pw:deagle, location=slot.weapon.mainhand}, scores={deagle=1..}] run function guns/deagle/fire
execute as @s[hasitem={item=pw:deagle, location=slot.weapon.mainhand}, scores={deagle=..0}] run scriptevent pw:gun_reload_deagle
execute as @s[hasitem={item=pw:fs, location=slot.weapon.mainhand}, scores={fs=1..}] run function guns/fs/fire
execute as @s[hasitem={item=pw:fs, location=slot.weapon.mainhand}, scores={fs=..0}] run scriptevent pw:gun_reload_fs
execute as @s[hasitem={item=pw:glock17, location=slot.weapon.mainhand}, scores={glock17=1..}] run function guns/glock17/fire
execute as @s[hasitem={item=pw:glock17, location=slot.weapon.mainhand}, scores={glock17=..0}] run scriptevent pw:gun_reload_glock17
execute as @s[hasitem={item=pw:p350, location=slot.weapon.mainhand}, scores={p350=1..}] run function guns/p350/fire
execute as @s[hasitem={item=pw:p350, location=slot.weapon.mainhand}, scores={p350=..0}] run scriptevent pw:gun_reload_p350
execute as @s[hasitem={item=pw:tec9, location=slot.weapon.mainhand}, scores={tec9=1..}] run function guns/tec9/fire
execute as @s[hasitem={item=pw:tec9, location=slot.weapon.mainhand}, scores={tec9=..0}] run scriptevent pw:gun_reload_tec9
execute as @s[hasitem={item=pw:usp, location=slot.weapon.mainhand}, scores={usp=1..}] run function guns/usp/fire
execute as @s[hasitem={item=pw:usp, location=slot.weapon.mainhand}, scores={usp=..0}] run scriptevent pw:gun_reload_usp
execute as @s[hasitem={item=pw:m1014, location=slot.weapon.mainhand}, scores={m1014=1..}] run function guns/m1014/fire
execute as @s[hasitem={item=pw:m1014, location=slot.weapon.mainhand}, scores={m1014=..0}] run scriptevent pw:gun_reload_m1014
execute as @s[hasitem={item=pw:sawedoff, location=slot.weapon.mainhand}, scores={sawedoff=1..}] run function guns/sawedoff/fire
execute as @s[hasitem={item=pw:sawedoff, location=slot.weapon.mainhand}, scores={sawedoff=..0}] run scriptevent pw:gun_reload_sawedoff
execute as @s[hasitem={item=pw:spas12, location=slot.weapon.mainhand}, scores={spas12=1..}] run function guns/spas12/fire
execute as @s[hasitem={item=pw:spas12, location=slot.weapon.mainhand}, scores={spas12=..0}] run scriptevent pw:gun_reload_spas12
execute as @s[hasitem={item=pw:mac10, location=slot.weapon.mainhand}, scores={mac10=1..}] run function guns/mac10/fire
execute as @s[hasitem={item=pw:mac10, location=slot.weapon.mainhand}, scores={mac10=..0}] run scriptevent pw:gun_reload_mac10
execute as @s[hasitem={item=pw:mp5, location=slot.weapon.mainhand}, scores={mp5=1..}] run function guns/mp5/fire
execute as @s[hasitem={item=pw:mp5, location=slot.weapon.mainhand}, scores={mp5=..0}] run scriptevent pw:gun_reload_mp5
execute as @s[hasitem={item=pw:mp7, location=slot.weapon.mainhand}, scores={mp7=1..}] run function guns/mp7/fire
execute as @s[hasitem={item=pw:mp7, location=slot.weapon.mainhand}, scores={mp7=..0}] run scriptevent pw:gun_reload_mp7
execute as @s[hasitem={item=pw:mp40, location=slot.weapon.mainhand}, scores={mp40=1..}] run function guns/mp40/fire
execute as @s[hasitem={item=pw:mp40, location=slot.weapon.mainhand}, scores={mp40=..0}] run scriptevent pw:gun_reload_mp40
execute as @s[hasitem={item=pw:p90, location=slot.weapon.mainhand}, scores={p90=1..}] run function guns/p90/fire
execute as @s[hasitem={item=pw:p90, location=slot.weapon.mainhand}, scores={p90=..0}] run scriptevent pw:gun_reload_p90
execute as @s[hasitem={item=pw:ppsh, location=slot.weapon.mainhand}, scores={ppsh=1..}] run function guns/ppsh/fire
execute as @s[hasitem={item=pw:ppsh, location=slot.weapon.mainhand}, scores={ppsh=..0}] run scriptevent pw:gun_reload_ppsh
execute as @s[hasitem={item=pw:thompson, location=slot.weapon.mainhand}, scores={thompson=1..}] run function guns/thompson/fire
execute as @s[hasitem={item=pw:thompson, location=slot.weapon.mainhand}, scores={thompson=..0}] run scriptevent pw:gun_reload_thompson
execute as @s[hasitem={item=pw:ump45, location=slot.weapon.mainhand}, scores={ump45=1..}] run function guns/ump45/fire
execute as @s[hasitem={item=pw:ump45, location=slot.weapon.mainhand}, scores={ump45=..0}] run scriptevent pw:gun_reload_ump45
execute as @s[hasitem={item=pw:awm, location=slot.weapon.mainhand}, scores={awm=1..}] run function guns/awm/fire
execute as @s[hasitem={item=pw:awm, location=slot.weapon.mainhand}, scores={awm=..0}] run scriptevent pw:gun_reload_awm
execute as @s[hasitem={item=pw:awm_scoped, location=slot.weapon.mainhand}, scores={awm=1..}] run function guns/awm/fire
execute as @s[hasitem={item=pw:awm_scoped, location=slot.weapon.mainhand}, scores={awm=..0}] run scriptevent pw:gun_reload_awm
execute as @s[hasitem={item=pw:kar98k, location=slot.weapon.mainhand}, scores={kar98k=1..}] run function guns/kar98k/fire
execute as @s[hasitem={item=pw:kar98k, location=slot.weapon.mainhand}, scores={kar98k=..0}] run scriptevent pw:gun_reload_kar98k
execute as @s[hasitem={item=pw:kar98k_scoped, location=slot.weapon.mainhand}, scores={kar98k=1..}] run function guns/kar98k/fire
execute as @s[hasitem={item=pw:kar98k_scoped, location=slot.weapon.mainhand}, scores={kar98k=..0}] run scriptevent pw:gun_reload_kar98k
execute as @s[hasitem={item=pw:m40, location=slot.weapon.mainhand}, scores={m40=1..}] run function guns/m40/fire
execute as @s[hasitem={item=pw:m40, location=slot.weapon.mainhand}, scores={m40=..0}] run scriptevent pw:gun_reload_m40
execute as @s[hasitem={item=pw:m40_scoped, location=slot.weapon.mainhand}, scores={m40=1..}] run function guns/m40/fire
execute as @s[hasitem={item=pw:m40_scoped, location=slot.weapon.mainhand}, scores={m40=..0}] run scriptevent pw:gun_reload_m40
execute as @s[hasitem={item=pw:m110, location=slot.weapon.mainhand}, scores={m110=1..}] run function guns/m110/fire
execute as @s[hasitem={item=pw:m110, location=slot.weapon.mainhand}, scores={m110=..0}] run scriptevent pw:gun_reload_m110
execute as @s[hasitem={item=pw:m110_scoped, location=slot.weapon.mainhand}, scores={m110=1..}] run function guns/m110/fire
execute as @s[hasitem={item=pw:m110_scoped, location=slot.weapon.mainhand}, scores={m110=..0}] run scriptevent pw:gun_reload_m110