execute as @s[tag=underground] run playsound effect.gun.indoors @a[rm=0, r=100] ^^0.5^1 100 1 0.01
execute as @s[hasitem={item=pw:ak12, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:ak47, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:ak74, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:akm, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:aug, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:famas, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:fnfal, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:m4, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:m16, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:sks, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar_semi @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:stg44, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.ar @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:m60, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.lmg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:rpg7, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.rocket @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:rpk, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.lmg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:colt_m1892, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.pistol @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:colt_python, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.pistol @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:deagle, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.pistol @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:fs, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.pistol @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:glock17, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.pistol @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:p350, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.pistol @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:tec9, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.pistol @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:usp, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.pistol @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:m1014, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:sawedoff, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:spas12, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:mac10, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.smg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:mp5, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.smg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:mp7, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.smg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:mp40, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.smg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:p90, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.smg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:ppsh, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.smg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:thompson, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.smg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:ump45, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.smg @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:awm, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:awm_scoped, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:kar98k, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:kar98k_scoped, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:m40, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:m40_scoped, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:m110, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01
execute as @s[hasitem={item=pw:m110_scoped, location=slot.weapon.mainhand}, tag=!underground] run playsound effect.gun.echo.any @a[rm=0, r=400] ^^0.5^1 400 1 0.01